.github/workflows/main.yml

The CI script contains a single job executed at a PR:
- installs all dependencies on Ubuntu latest
- builds pdf
- builds html
The job runs in the pr_ci environment.
The expectation is that this environment requires the maintainer team to release the job (relies on the GitHub project configuration).

Create basic CI

---

.github/workflows/main.yml

The changes in #1 caused the pdf archiving in the CI to fail. Use lower case output filename to match the changes in #1.

Use lower case filename in main.yml

---

source/transfer_list.rst

This patch fixes a mistake that crept in during review of PR #6 (patch 062d542). The `alignment_offset` calculated from `tl_base_addr` was not superfluous in that calculation -- in fact, this is the only way in which `tl_base_addr` entered the calculation at all. If we don't have this, relocation for base addresses that do not already happen to match the highest alignment requirement won't work.
Also fix another small mistake in the same algorithm regarding calculating the new `tl.max_size`.

Fix relocation algorithm description

---

source/transfer_list.rst

In the algorithm instructions for reading a TL, we forgot aligning the next TE base address. This patch fixes the description.

Add TE base alignment step to algorithm for reading a TL

---

source/transfer_list.rst

For TEs with special alignment requirement, the point is to align the data portion, not the TE header. This needs to be taken into account when calculating how much padding needs to be inserted to reach the correct alignment. This patch fixes the algorithm description for adding aligned TEs to account for that.

Account for TE header in algorithm to add an aligned TE

---

source/register_conventions.rst
source/transfer_list.rst

The current signature value is 0x40_b10b
We actually have 4 bytes for the signature, so having one byte as zero is not ideal.
Adopt 4a0f_b10b (meaning "handoff blob") instead.
Fixes: #21

Change checksum to 4a0f_b10b

---

source/references.rst
source/transfer_list.rst

This entry will have information related to TPM event log and CRB buffer.

Add new entry for TPM info

---

source/images/handoff_list_diagram.svg
source/transfer_list.rst

The word 'size' is pretty generic and appears through the spec. It refers to the about of space currently used by the TEs, so rename it to used_size
The term `max_size` is a little confusing since it is really the current size of the TL including its spare space. Rename this to total_size indicating that is the total of all TEs and space space.
It also happens to match the devicetree terminology.
Fixes: #22

Adjust terminoloy for size

---

source/register_conventions.rst

Although x1 and r1 refer to the same register, technically x1 is the name of the register in the Aarch64 instruction set. We ought to stick to convention to avoid any confusion.

Fix typo in Aarch32 register convention description

---

source/transfer_list.rst

`pp_addr` is a 64-bit address, using `data_size` in its size field implies that it is variable sized. Replace the variable with its fixed size for clarity.

Fix OP-TEE pageable part data size

---

source/transfer_list.rst

XFERLIST_RW_MEM_LAYOUT64 is used to specify an extent of read-write memory that a client can use. Note, in future if other memory types need representation seperate TE's should be defined (left in the layout description as a point of discussion).

Add RW memory layout TE

---

source/references.rst

Each of the footnote references either had broken hyperlink syntax or no hyperlink at all. Add/fix links as appropriate.

Fix embedded hyperlinks in references

---

source/references.rst
source/transfer_list.rst

Add a new TE entry type for executable entry point information to TF-A's entry range. This entry type contains data about the execution state of images (i.e. PC, SPSR values), which can be used by a consumer to execute those images.

Add executable entrypoint information TE entry

---

.github/workflows/main.yml

Move up GitHub actions version to v4 in main.yml to avoid build warning, as per:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

Move up GitHub actions to v4

---

source/transfer_list.rst

Tag ID of RW memory layout entry was wrongly put as "104" instead of "0x104".

Fix tag ID of RW memory layout entry

---

source/register_conventions.rst

Commit d6afd9b updated the signature from 3 bytes to 4 bytes, but didn't update the register_conventions accordingly.
For AArch64 mode represent whole 4 bytes of signature in register X1 while for AArch32 mode use only 3 least significant bytes of signature.

Fix register convention for 4 byte signature

---

source/register_conventions.rst

The table describing the Aarch32 register convention is missing vertical bar seperators in several places. Add those seperators back to fix the documentation build errors.

Fix malformed reg convention table

---

source/transfer_list.rst

This PR introduces a TE to communicate details about the memory allocated for Mbed-TLS’s dynamic memory management. The buffer, described by the TE, is zero-initialised and intended for internal stack-based memory allocation by the library [1]. It's address and size are used by subsequent layers during the intialisation of Mbed-TLS.
[1] https://arm-software.github.io/CMSIS-mbedTLS/latest/memory__buffer__alloc_8h.html#ac70d134be54133c272d8eab2cb85dfbf

Add Mbed-TLS crypto heap info entry

---

source/references.rst
source/transfer_list.rst

The full rationale can be found in issue [51](https://github.com/FirmwareHandoff/firmware_handoff/issues/51).
This pull request concerns adding a dedicated data type for an SP binary and making the SPMC manifest TE type more generic, to be used as the SP's FF-A manifest.
This allows the Hafnium SPMC to use the TL format to package SP's artefacts.

FF-A manifest and SP binary TE types

---

source/register_conventions.rst

Fix the reference to the AArch64 table in the first paragraph of chapter "AArch64 Receiver".
Signed-off-by: Bence Csókás <bence98@sch.bme.hu>

register_conventions: Fix table reference

---

contributing.rst
source/introduction.rst
source/transfer_list.rst

The IETF RFC2119 defines terms for requirements and guidance statements. This commit changes the spec to adopt those terms, where relevant, and requires future contributions to comply with RFC2119.
Fix #30
Change-Id: Ia4cc7f44bcd4508025f30d2410e83802c6ec4a11

Adopt RFC2119 terms for requirements language

---

source/_static/css/custom.css
source/conf.py
source/register_conventions.rst
source/transfer_list.rst

Couple of minor refactoring patches to improve the display of information listed under tables on html.

Enhance the listing of Tables in html

---

source/transfer_list.rst

Add TL rules:
- TE types may allow multiple entries, provided that they contain a sub-type field.
- For all the TE types that do not allow multiple entries, the TL must contain at most a TE of that type.
Change-Id: Ie88ce9f1eb7efb9065bd6f9059739e363f84055d

Allow N entries of same type, if sub-type defined

---

source/transfer_list.rst

Adds 32-bit versions of the XFERLIST_RW_MEM_LAYOUT and XFERLIST_EP_INFO structures to support booting on 32-bit Arm (aarch32) systems, and corrects the Mbed-TLS heap info heading to fall under the Arm subsection.

Add 32-bit variants for XFERLIST_SRAM_LAYOUT and XFERLIST_EP_INFO

---

source/references.rst

The references point to external documents that can evolve. It's important the external referenced concepts are static.
To achieve that, the list of references is being updated to reference a well defined version of the external document.
Change-Id: I8664df5f8f09b56ce3d01f22d122253e295a3820

Pin references to a particular version.

---

source/register_conventions.rst
source/transfer_list.rst

The specification used different conventions to represent field values. This commit homogenizes all filed values to be represented with backticks.
Change-Id: I4db4e1e226a2780813b07457f33db4294a7f5da7

Homogenize typographical conventions

---

source/transfer_list.rst

Update requirement R1 to specify that tl_base_pa must be both non-zero address and 8-byte aligned.
Fixes #67

Clarify alignment requirement for tl_base_pa to specify it must be non-zero and at a 8-byte boundary

---

.github/workflows/daily.yml
README.md

Create a scheduled job to run nightly, ensuring documentation builds and links are validated and errors are caught early.
Fixes #64

Add nightly job to test doc builds and links

---

source/transfer_list.rst

Both `XFERLIST_DT_FFA_MANIFEST` and `XFERLIST_EXEC_EP_INFO32` were erroneously assigned the tag ID 0x106. Since `XFERLIST_EXEC_EP_INFO32` is newer and not yet widely used, its tag ID is updated to 0x107 to resolve the conflict.
Additionally, fix the field layout for the 32-bit EP_INFO entry: register offsets were misaligned due to an incorrect header size assumption. Each member is adjusted by 0x4 to align correctly with the actual size of param_header_h.
Also, add the layout definition for the 64-bit EP_INFO entry type to complete the specification.

Fix ep-Info field offsets and add 64-bit fields

---

source/transfer_list.rst

This PR introduces a summary table listing all Trusted Firmware transfer list
entry types, improving spec readability and aiding error detection. It also
corrects the tag ID of XFERLIST_EXEC_EP_INFO32 to 0x108 and reorders the
section accordingly.

Add TF-A entry types summary table and fix XFERLIST_EXEC_EP_INFO32 tag ID

---

source/conf.py

Adds linkcheck_ignore for https://uefi.org/specs/* URLs to avoid 403 errors [1] when checking links via GitHub CI. Site access appears restricted, causing false linkcheck failures.
[1] https://github.com/FirmwareHandoff/firmware_handoff/actions/runs/14632508665/job/41057250230#step:6:36

Ignore uefi.org links during linkcheck

---

source/transfer_list.rst

There is a new entry to add in transfer list. This is for the primary GPT corruption logging, which use the transfer list to pass the information from BL2 to BL32.

Update specification for transfer list with GPT info tag
